spring:
  datasource:
    url: jdbc:postgresql://server:5432/sys_pequeno
    username: postgres
    password: adminpg

jpa:
    hibernate:
             ddl-auto: update # Use la actualización después de la primera creación del perfil
    show-sql: true
