spring:
  datasource:
    url: jdbc:postgresql://servidor:5432/sys_agroprogreso
    username: postgres
    password: adminpg

jpa:
    hibernate:
             ddl-auto: update # Use la actualización después de la primera creación del perfil
    show-sql: true
