spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sys_farmacia_sjn
    username: postgres
    password: adminpg

jpa:
    hibernate:
             ddl-auto: update # Use la actualización después de la primera creación del perfil
    show-sql: true
